// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  decsription: defineAsyncComponent(() => import("./Description/index.vue")),
  footer_link: defineAsyncComponent(() => import("./FooterLink/index.vue")),
});
